# Generated by Django 3.1.4 on 2020-12-14 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicemod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Usermod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Телефон', max_length=31)),
                ('name_org', models.CharField(max_length=255, verbose_name='Название организации')),
                ('address_org', models.CharField(max_length=255, verbose_name='Адрес организации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователи услуг',
                'verbose_name_plural': 'Пользователи услуг',
            },
        ),
        migrations.CreateModel(
            name='Ordermod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateField(blank=True, null=True, verbose_name='Дата заказа')),
                ('executed_order', models.BooleanField(default=True, verbose_name='Выполнен: да/нет')),
                ('servicemod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderschema.servicemod')),
                ('usermod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderschema.usermod')),
            ],
            options={
                'verbose_name': 'Зкаказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
    ]
