# Generated by Django 3.1.4 on 2020-12-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderschema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermod',
            name='phone',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
    ]
