# Generated by Django 3.1.4 on 2020-12-15 11:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orderschema', '0002_auto_20201215_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermod',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
