# Generated by Django 3.1.4 on 2020-12-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderschema', '0006_remove_usermod_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermod',
            name='mobile_phone',
            field=models.CharField(default='SOME STRING', max_length=12, unique=True, verbose_name='Телефон +7'),
        ),
    ]
