# Generated by Django 3.1.4 on 2020-12-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderschema', '0007_usermod_mobile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermod',
            name='mobile_phone',
            field=models.CharField(default='Мобильник', max_length=12, unique=True, verbose_name='Телефон +7'),
        ),
    ]
