# Generated by Django 3.1.4 on 2020-12-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderschema', '0008_auto_20201216_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermod',
            name='mobile_phone',
            field=models.CharField(default='', max_length=12, unique=True, verbose_name='Телефон +7'),
        ),
    ]
