# Generated by Django 3.1.4 on 2020-12-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderschema', '0009_auto_20201219_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermod',
            name='date_order',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата заказа'),
        ),
    ]
